### ISSUE TITLE
大佬能把dev分支支持一下5.4内核么？

### ISSUE THREAD

**Issue by luovivi** [CHN-beta/xmurp-ua#10]
我用master分支的makefile文件替换了dev分支的，可以编译成功但是路由器无法启动。

**Comment by CHN-beta** [comment]
抱歉，刚刚才看见……
我下午适配吧

**Comment by CHN-beta** [comment]
修啦，你再试试看行不行？

**Comment by luovivi** [comment]
> 修啦，你再试试看行不行？

可以编译成功也能安装，但是好像没有生效，日志里没有启动记录，http的ua查询网站也还是显示原始UA。路由器硬件加速也关了

**Comment by CHN-beta** [comment]
> > 修啦，你再试试看行不行？
> 
> 可以编译成功也能安装，但是好像没有生效，日志里没有启动记录，http的ua查询网站也还是显示原始UA。路由器硬件加速也关了

dev 分支的因为还不够稳定，所以没有设置自动加载模块（这样，万一挂掉，重启一下路由器就恢复了，不需要重刷）。

手动加载：insmod xmurp-ua

具体其它的内容看文档。在 doc 里。文档还有一点点写错的地方，还没来得及改。合并到 master 之前会改的。

**Comment by luovivi** [comment]
> > > 修啦，你再试试看行不行？
> > 
> > 
> > 可以编译成功也能安装，但是好像没有生效，日志里没有启动记录，http的ua查询网站也还是显示原始UA。路由器硬件加速也关了
> 
> dev 分支的因为还不够稳定，所以没有设置自动加载模块（这样，万一挂掉，重启一下路由器就恢复了，不需要重刷）。
> 
> 手动加载：insmod xmurp-ua
> 
> 具体其它的内容看文档。在 doc 里。文档还有一点点写错的地方，还没来得及改。合并到 master 之前会改的。

感谢大佬！成功啦
