### ISSUE TITLE
这个模块是只修改80端口的流量吗？

### ISSUE THREAD

**Issue by Zxilly** [CHN-beta/xmurp-ua#13]
https://github.com/CHN-beta/xmurp-ua/blob/75fdf912a570eaa0e605317e9d6092936fb3fabe/src/rkpSetting.h#L36-L40

https://github.com/CHN-beta/xmurp-ua/blob/75fdf912a570eaa0e605317e9d6092936fb3fabe/src/rkpSetting.h#L59

https://github.com/CHN-beta/xmurp-ua/blob/258dd610ef508eb2b52cacc68671706e442b9f39/src/xmurp-ua.c#L173

主要是今天同学买了GSWIFI的路由器，我做了一些测试，连`http://wdnmd.kask.top:31666/ua.php`的http连接都能检测出来修改UA，想不通怎么做到的，心情略崩溃。

我尝试使用过ndpi来识别http流量，但是那个的作者告诉我这无法实现
`https://github.com/vel21ripn/nDPI/issues/102`

**Comment by CHN-beta** [comment]
是的，只改80。
要判断的话，看 TCP 的 payload 是否以 HTTP 开头应该就可以。但是我没写这个功能。

**Comment by Zxilly** [comment]
是否可能用iptables的string filter来匹配GET和POST这两个字符串，从而转发呢？
还是说匹配到以后要给整条流打上MARK再转发流？
http的报文里好像没有http这个字段吧

**Comment by Zxilly** [comment]
明白了，协议里面有HTTP。。。

**Comment by CHN-beta** [comment]
要在iptables操作的话，肯定是需要对整个流操作的。
