### ISSUE TITLE
Cannot install package kmod-xmurp-ua

### ISSUE THREAD

**Issue by arbaleast** [CHN-beta/xmurp-ua#14]
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-xmurp-ua:
 * 	kernel (= 4.14.221-1-18384755d38fc43c447d83d4a3e07054)
 * opkg_install_cmd: Cannot install package kmod-xmurp-ua.

---
root@OpenWrt:/tmp/tmp# cat /proc/version
Linux version 5.4.50 (zheshifandian@HP-Pavilion-15) (gcc version 8.4.0 (OpenWrt GCC 8.4.0 r2813-3f8a99632)) #0 Fri Jul 10 02:50:02 2020
请问该如何更新这个kernel

**Comment by CHN-beta** [comment]
用你的镜像对应的SDK来编译，就不会出现这个问题。

实在没有SDK的话，也可以参考[这里](https://catalog.chn.moe/%E6%8A%80%E6%9C%AF/OpenWrt/%E7%BC%96%E8%AF%91/#%E6%97%A0-SDK-%E7%BC%96%E8%AF%91%E8%BD%AF%E4%BB%B6%E5%8C%85)直接改依赖试试。

> opkg 在安装软件包时，会检查内核版本和内核的设置的 hash 是否与编译时一致（原理是，在软件包中写入一条类似于 kernel - 4.14.180-1-fa00c1231ac7d7840ec6ffe62dcad926 这样的依赖）。使用相近的 SDK，编译后使用 archivemount 或者其它可以修改压缩包内容的工具打开编译出来的软件包，在 control.tar.gz 里再打开 control，改一下依赖即可。

要直接更新内核的话，最好的办法是重刷。。。

**Comment by arbaleast** [comment]
> 用你的镜像对应的SDK来编译，就不会出现这个问题。
> 
> 实在没有SDK的话，也可以参考[这里](https://catalog.chn.moe/%E6%8A%80%E6%9C%AF/OpenWrt/%E7%BC%96%E8%AF%91/#%E6%97%A0-SDK-%E7%BC%96%E8%AF%91%E8%BD%AF%E4%BB%B6%E5%8C%85)直接改依赖试试。
> 
> > opkg 在安装软件包时，会检查内核版本和内核的设置的 hash 是否与编译时一致（原理是，在软件包中写入一条类似于 kernel - 4.14.180-1-fa00c1231ac7d7840ec6ffe62dcad926 这样的依赖）。使用相近的 SDK，编译后使用 archivemount 或者其它可以修改压缩包内容的工具打开编译出来的软件包，在 control.tar.gz 里再打开 control，改一下依赖即可。
> 
> 要直接更新内核的话，最好的办法是重刷。。。

谢谢回复，官方提供了SDK，我重新编译试试

**Comment by CHN-beta** [comment]
没问题的话，我把issue关掉了哈

**Comment by arbaleast** [comment]
> 没问题的话，我把issue关掉了哈

好，谢谢
