### ISSUE TITLE
建议适配 Padavan

### ISSUE THREAD

**Issue by 0xffffharry** [CHN-beta/xmurp-ua#15]
Padavan的无线性能简直吊打Openwrt，但是好像GitHub上的Padavan项目中并没有找到可以更改UA的插件，决定自己动手时，我尝试各个分支，都不能成功编译成内核模块（吐槽一波Padavan的内核实在太旧了，都2022还在用 linux 3.x），希望可以对Padavan增加支持

**Comment by CHN-beta** [comment]
> Padavan的无线性能简直吊打Openwrt，但是好像GitHub上的Padavan项目中并没有找到可以更改UA的插件，决定自己动手时，我尝试各个分支，都不能成功编译成内核模块（吐槽一波Padavan的内核实在太旧了，都2022还在用 linux 3.x），希望可以对Padavan增加支持

难道现在不支持padavan吗？

**Comment by imguoliwei** [comment]
> Padavan的无线性能简直吊打Openwrt，但是好像GitHub上的Padavan项目中并没有找到可以更改UA的插件，决定自己动手时，我尝试各个分支，都不能成功编译成内核模块（吐槽一波Padavan的内核实在太旧了，都2022还在用 linux 3.x），希望可以对Padavan增加支持

你可以尝试[UA2F-cpp](https://github.com/imguoliwei/UA2F-cpp)，这是一个用户程序

**Comment by 0xffffharry** [comment]
> > Padavan的无线性能简直吊打Openwrt，但是好像GitHub上的Padavan项目中并没有找到可以更改UA的插件，决定自己动手时，我尝试各个分支，都不能成功编译成内核模块（吐槽一波Padavan的内核实在太旧了，都2022还在用 linux 3.x），希望可以对Padavan增加支持
> 
> 难道现在不支持padavan吗？

padavan编译过不了。。。

大佬有空可以帮忙看看吗，hanwckf/rt-n56u 这个版本的padavan，感谢

**Comment by CHN-beta** [comment]
> hanwckf/rt-n56u

方便给个链接吗？我没找到SDK下载地址。

**Comment by 0xffffharry** [comment]
> > hanwckf/rt-n56u
> 
> 方便给个链接吗？我没找到SDK下载地址。

没有sdk，只有源码，源码里面可以下载预编译链

https://github.com/hanwckf/rt-n56u

**Comment by CHN-beta** [comment]
> > > hanwckf/rt-n56u
> > 
> > 
> > 方便给个链接吗？我没找到SDK下载地址。
> 
> 没有sdk，只有源码，源码里面可以下载预编译链
> 
> https://github.com/hanwckf/rt-n56u

看了看编译方式，感觉太野了，sudo 满天飞，不敢在自己电脑上尝试。也懒得专门装一个虚拟机折腾。

对于openwrt官方的源码来说，make menuconfig 可以看到一个是否打包SDK的选项，钩上再编译系统时，就会自动把SDK也打包出来。有空的话，可以打包一个SDK出来，我给你编译。

之前有人给我[这里](http://downloads.pangubox.com:6380/pandorabox/)的SDK，我尝试是可以编译过的。不过我不懂这里的pangubox和你给的pandavan是不是同一个东西。

**Comment by 0xffffharry** [comment]
纠正：pangubox其实就是以前的Pandorabox，是openwrt一系

padavan源码写的很狂野，很多变量都写死在程序里面，后期其实根本不能修改（可能也是这个原因，padavan才比较稳定吧），实在无从下手，只能是看看能不能在内核编译的时候下手，把xmurp-ua编译成ko内核模块，在开机时装载。

还有一点就是dev分支有大概率死机的问题，今天重启两次，手上的是红米2100（Redmi AC2100 | MT7621）

**Comment by CHN-beta** [comment]
> 

重启这个太正常了，当年我水平还比较渣。当然现在写出来的代码也没那个完美，有个没开源的项目也是饱受内存泄漏的折磨（不过不至于直接挂掉）。

**Comment by 0xffffharry** [comment]
```
vm@vm:/mnt/data/code/rt-n56u/trunk/linux-3.4.x$ export ARCH=mips
vm@vm:/mnt/data/code/rt-n56u/trunk/linux-3.4.x$ export CROSS_COMPILE=/mnt/data/code/rt-n56u/toolchain-mipsel/toolchain-3.4.x/bin/mipsel-linux-uclibc-
vm@vm:/mnt/data/code/rt-n56u/trunk/linux-3.4.x$ make M=net/xmurp-ua/ CONFIG_XMURP_UA=m modules
  CC [M]  net/xmurp-ua//xmurp-ua.o
net/xmurp-ua//xmurp-ua.c: In function 'hook_init':
net/xmurp-ua//xmurp-ua.c:276:12: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
  nfho.hook = hook_funcion;
            ^
net/xmurp-ua//xmurp-ua.c:285:45: error: 'VERSION' undeclared (first use in this function); did you mean 'IPVERSION'?
  printk("xmurp-ua: Started, version %d.\n", VERSION);
                                             ^~~~~~~
                                             IPVERSION
net/xmurp-ua//xmurp-ua.c:285:45: note: each undeclared identifier is reported only once for each function it appears in
cc1: some warnings being treated as errors
scripts/Makefile.build:313: recipe for target 'net/xmurp-ua//xmurp-ua.o' failed
make[1]: *** [net/xmurp-ua//xmurp-ua.o] Error 1
Makefile:1416: recipe for target '_module_net/xmurp-ua/' failed
make: *** [_module_net/xmurp-ua/] Error 2
vm@vm:/mnt/data/code/rt-n56u/trunk/linux-3.4.x$
```

Padavan工具链 Linux 3.4.X 编译失败

**Comment by CHN-beta** [comment]
> ```
> vm@vm:/mnt/data/code/rt-n56u/trunk/linux-3.4.x$ export ARCH=mips
> vm@vm:/mnt/data/code/rt-n56u/trunk/linux-3.4.x$ export CROSS_COMPILE=/mnt/data/code/rt-n56u/toolchain-mipsel/toolchain-3.4.x/bin/mipsel-linux-uclibc-
> vm@vm:/mnt/data/code/rt-n56u/trunk/linux-3.4.x$ make M=net/xmurp-ua/ CONFIG_XMURP_UA=m modules
>   CC [M]  net/xmurp-ua//xmurp-ua.o
> net/xmurp-ua//xmurp-ua.c: In function 'hook_init':
> net/xmurp-ua//xmurp-ua.c:276:12: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
>   nfho.hook = hook_funcion;
>             ^
> net/xmurp-ua//xmurp-ua.c:285:45: error: 'VERSION' undeclared (first use in this function); did you mean 'IPVERSION'?
>   printk("xmurp-ua: Started, version %d.\n", VERSION);
>                                              ^~~~~~~
>                                              IPVERSION
> net/xmurp-ua//xmurp-ua.c:285:45: note: each undeclared identifier is reported only once for each function it appears in
> cc1: some warnings being treated as errors
> scripts/Makefile.build:313: recipe for target 'net/xmurp-ua//xmurp-ua.o' failed
> make[1]: *** [net/xmurp-ua//xmurp-ua.o] Error 1
> Makefile:1416: recipe for target '_module_net/xmurp-ua/' failed
> make: *** [_module_net/xmurp-ua/] Error 2
> vm@vm:/mnt/data/code/rt-n56u/trunk/linux-3.4.x$
> ```
> 
> Padavan工具链 Linux 3.4.X 编译失败

看起来 3.4 早在 2016 年 10 月就停止维护了，我个人不愿意再花时间去适配这么老的版本。最近事情也比较多。

单纯看编译出错的信息的话，第二个错误很好解决，直接把那一句代码删掉就行；第一个错误的话，你得看一下 3.4 的内核头文件是怎么定义 `nf_hook_ops::hook` 的，对应着改一下 `hook_funcion` 的定义就行（内核 4.2 版本前后也有对这个指针的定义修改过，仿照着那个写就行）。

**Comment by 0xffffharry** [comment]
不会C，大佬有空就帮忙改改，没空就算了。

**Comment by a158566154** [comment]
虽然这个议题关闭了，这几天兴趣突发，已经把rtk-ipid移植到pandavan(kernel=3.4.x),过几天尝试移植该项目，这个issus对我的帮助挺大，谢谢作者！
