### ISSUE TITLE
Can you add a logo to your project?

### ISSUE THREAD

**Issue by YeWenxuan64** [CHN-beta/xmurp-ua#17]
Can you add a logo to your project? I'm running out of materials to introduce the history of this project.（；´д｀）ゞ
(If this issue is bothering you, then close it.(´。＿。｀))

**Comment by CHN-beta** [comment]
I am very pleased to hear that you try to write something to introduce history 😊.
However I am no idea about how to design a logo. If you really want a logo, you could design one and make a pr.
