### ISSUE TITLE
提议

### ISSUE THREAD

**Issue by Subdue0** [CHN-beta/xmurp-ua#5]
首先非常感谢大佬适配4.14内核，编译通过。
统一ua有挺多弊端的，很多需要特殊ua的都通过不了，我想问下，把数据包的“Android”替换成Windows会不会好点，当然这只是我的个人想法，大佬不想弄，可以不必理会

**Comment by Subdue0** [comment]
我尝试了下privoxy这样做没啥大问题，当然可能是我测试不够全面，不过这样做，那些需要特殊ua的站点就不会受到影响了

**Comment by CHN-beta** [comment]
我记得曾经这样试过，发现会导致手机上知乎的网页端无法唤起app，ua全改掉反而可以。

另外，检测不一定是Android关键字。之前我的手机刷了原生，怎么用都没事；一个舍友回来后，用他的flyme平板，十分钟内必掉。所以我也不知道到底检测的什么字段，干脆全改掉吧。

你想只替换android为Windows的话，自己改一下代码就好。c语言写的，不难，只是烦一些。

**Comment by Subdue0** [comment]
我试了下，android替换成windows，结果朋友圈图片没办法显示了，好像没有啥完美的解决方法了😂

**Comment by Subdue0** [comment]
大佬，我试了很多次还是没改好，求帮忙，s@\b(Android|iP\w+)\b@Windows NT@ig

**Comment by CHN-beta** [comment]
需要特殊ua的，用iptables放行即可。
