### ISSUE TITLE
启用flow offloading后模块失效

### ISSUE THREAD

**Issue by WordlessEcho** [CHN-beta/xmurp-ua#6]
设备：歌华链路由
版本：OpenWrt SNAPSHOT r11254-54d9ac8ba8

已按照[README](https://github.com/CHN-beta/xmurp-ua/blob/master/README.md)添加iptables规则，两行规则均分别尝试过

**Comment by CHN-beta** [comment]
> 设备：歌华链路由
> 版本：OpenWrt SNAPSHOT r11254-54d9ac8ba8
> 
> 已按照[README](https://github.com/CHN-beta/xmurp-ua/blob/master/README.md)添加iptables规则，两行规则均分别尝试过

我在我的教程上已经说过了，启用会失效。这不是我的锅。

并且在 README.md 里说了，对除了 http 以外的流量启用的方法。

有什么问题吗？

**Comment by CHN-beta** [comment]
> 设备：歌华链路由
> 版本：OpenWrt SNAPSHOT r11254-54d9ac8ba8
> 
> 已按照[README](https://github.com/CHN-beta/xmurp-ua/blob/master/README.md)添加iptables规则，两行规则均分别尝试过

好的。我写的规则有误。马上改正。
