### ISSUE TITLE
MWAN3可能导致修改失败

### ISSUE THREAD

**Issue by mr-cn** [CHN-beta/xmurp-ua#7]
一直没有效果，日志显示`xmurp-ua: Mark matched. Note that all packages with the mark will be ACCEPT without modification.`
把MWAN在WAN上的”已启用“选项关闭就好了

**Comment by CHN-beta** [comment]
MWAN3 也是使用 mark 来标记路由的，并且默认占用了 0x100 位。

请按照内核日志中下一句的提示，修改这个插件的源代码（使用别的位或者删掉这个功能）然后重新编译安装，或者修改 MWAN3 的 mark mask，让它不要占用这个位。

**Comment by mr-cn** [comment]
> MWAN3 也是使用 mark 来标记路由的，并且默认占用了 0x100 位。
> 请按照内核日志中下一句的提示，修改这个插件的源代码（使用别的位或者删掉这个功能）然后重新编译安装，或者修改 MWAN3 的 mark mask，让它不要占用这个位。

我暂时用不到MWAN，直接关掉了。发上来是为了给后来的朋友一个可能的方向。
