### ISSUE TITLE
插件安装失败，请问该怎么处理呢

### ISSUE THREAD

**Issue by hxq7426** [CHN-beta/xmurp-ua#8]
大佬你好，我使用的是官方openwrt18.06.0，4.14.54的内核，我在网上找了几个这种插件都安装失败了。不知道该怎么处理。希望能指点迷津。

**Comment by CHN-beta** [comment]
是不是版本找错了？具体说说，什么型号，装哪个版本出错了？

**Comment by hxq7426** [comment]
感谢回复，是我的路由器刷的系统太低了，内核版本不支持。我现在用的是softether vpn server来绕过认证。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;陈浩南&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月9日(星期四) 凌晨0:01
收件人:&nbsp;&quot;CHN-beta/xmurp-ua&quot;<xmurp-ua@noreply.github.com&gt;;
抄送:&nbsp;&quot;hxqwxf&quot;<1401115960@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CHN-beta/xmurp-ua] 插件安装失败，请问该怎么处理呢 (#8)

**Comment by CHN-beta** [comment]
> 感谢回复，是我的路由器刷的系统太低了，内核版本不支持。我现在用的是softether vpn server来绕过认证。------------------&nbsp;原始邮件&nbsp;------------------
> 发件人:&nbsp;&quot;陈浩南&quot;<notifications@github.com&gt;
> 发送时间:&nbsp;2020年7月9日(星期四) 凌晨0:01
> 收件人:&nbsp;&quot;CHN-beta/xmurp-ua&quot;<xmurp-ua@noreply.github.com&gt;;
> 抄送:&nbsp;&quot;hxqwxf&quot;<1401115960@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
> 主题:&nbsp;Re: [CHN-beta/xmurp-ua] 插件安装失败，请问该怎么处理呢 (#8)

内核版本多少？我添加一下支持。

**Comment by hxq7426** [comment]
> > 感谢回复，是我的路由器刷的系统太低了，内核版本不支持。我现在用的是softether vpn server来绕过认证。原始邮件------------------ 
> > 发件人：“陈浩南” < [notifications@github.com](mailto:notifications@github.com) > 
> > 发送时间：2020年7月9日（星期四）凌晨0:01 
> > 收件人：“ CHN-beta / xmurp-ua” < [xmurp-ua@noreply.github.com](mailto:xmurp-ua@noreply.github.com) >; 
> > 抄送：“ hxqwxf” < [1401115960@qq.com](mailto:1401115960@qq.com) >;“作者” < [author@noreply.github.com](mailto:author@noreply.github.com) >; 
> > 主题：Re：[CHN-beta / xmurp-ua]插件安装失败，请问该怎么处理呢（[＃8](https://github.com/CHN-beta/xmurp-ua/issues/8)）
> 
> 内核版本多少？我添加一下支持。

谢谢，不用麻烦了，我已经忘了具体型号了。我现在使用的是VPN方法来绕过认证
