### ISSUE TITLE
大佬，插件在5.4内核上编译失败，求更新

### ISSUE THREAD

**Issue by luovivi** [CHN-beta/xmurp-ua#9]
make[3]: Entering directory '/workdir/openwrt/package/xmurp-ua'
rm -rf /workdir/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/xmurp-ua/.pkgdir/kmod-xmurp-ua.installed /workdir/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/xmurp-ua/.pkgdir/kmod-xmurp-ua
mkdir -p /workdir/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/xmurp-ua/.pkgdir/kmod-xmurp-ua
ERROR: module '/workdir/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/xmurp-ua/xmurp-ua.ko' is missing.
make[3]: *** [/workdir/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/xmurp-ua/.pkgdir/kmod-xmurp-ua.installed] Error 1
Makefile:31: recipe for target '/workdir/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/xmurp-ua/.pkgdir/kmod-xmurp-ua.installed' failed
make[3]: Leaving directory '/workdir/openwrt/package/xmurp-ua'
time: package/xmurp-ua/compile#0.14#0.04#0.19
package/Makefile:111: recipe for target 'package/xmurp-ua/compile' failed
make[2]: Leaving directory '/workdir/openwrt'
make[2]: *** [package/xmurp-ua/compile] Error 2
make[1]: *** [/workdir/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
package/Makefile:107: recipe for target '/workdir/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile' failed
make[1]: Leaving directory '/workdir/openwrt'
/workdir/openwrt/include/toplevel.mk:222: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by CHN-beta** [comment]
更新了，看看这次行不行。我测试已经没问题了。

**Comment by luovivi** [comment]
成功了，感谢大佬！
